--
-- Program memory ROM implemented using a case statement.
-- Its content was generated by the microCore cross compiler.
-- It will be statically synthesized into the design as cold bootrom.

LIBRARY IEEE;
USE     IEEE.STD_LOGIC_1164.ALL;
USE     IEEE.NUMERIC_STD.ALL;
USE     work.architecture_pkg.ALL;

ENTITY boot_rom IS PORT (
   addr  : IN   boot_addr_bus;
   data  : OUT  inst_bus
); END boot_rom;

ARCHITECTURE sim_model OF boot_rom IS

SUBTYPE rom_address IS NATURAL RANGE 0 TO 2**boot_addr_width-1;

FUNCTION program(addr : rom_address) RETURN UNSIGNED IS
BEGIN
   CASE addr IS
      WHEN 16#0000# => RETURN "10000000";
      WHEN 16#0001# => RETURN "00000000";
      WHEN 16#0002# => RETURN "11111110";
      WHEN 16#0003# => RETURN "00001001";
      WHEN 16#0004# => RETURN "01011101";
      WHEN OTHERS   => RETURN "--------";
   END CASE;
END program;

BEGIN

data <= program(to_integer(addr));

END sim_model;