--
-- Program memory ROM implemented using a case statement.
-- It is generated by the microCore cross compiler.

LIBRARY IEEE;
USE     IEEE.STD_LOGIC_1164.ALL;
USE     IEEE.NUMERIC_STD.ALL;
USE     work.architecture_pkg.ALL;

ENTITY program_rom IS PORT (
   addr  : IN   program_addr;
   data  : OUT  inst_bus
); END program_rom;

ARCHITECTURE sim_model OF program_rom IS

SUBTYPE rom_address IS NATURAL RANGE 0 TO 2**prog_addr_width-1;

FUNCTION program(addr : rom_address) RETURN UNSIGNED IS
BEGIN
   CASE addr IS
      WHEN 16#0000# => RETURN "10000001";
      WHEN 16#0001# => RETURN "10101010";
      WHEN 16#0002# => RETURN "11010101";
      WHEN 16#0003# => RETURN "00000000";
      WHEN 16#0004# => RETURN "10000100";
      WHEN 16#0005# => RETURN "00000000";
      WHEN 16#0006# => RETURN "01001000";
      WHEN 16#0007# => RETURN "01010000";
      WHEN 16#0008# => RETURN "11111100";
      WHEN 16#0009# => RETURN "00001001";
      WHEN 16#000A# => RETURN "01011101";
      WHEN OTHERS   => RETURN "--------";
   END CASE;
END program;

BEGIN

data <= program(to_integer(addr));

END sim_model;